name: DEPLOY TO EC2 - GITHUB ACTIONS
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude="node_modules" --exclude=".git" --exclude="database.sql"
        path: src/server
        remote_path: /home/ubuntu/app
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
  