name: DEPLOY TO EC2 - GITHUB ACTIONS
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --include={"db.js", "index.js", "package-lock.json", "package.json"} --exclude={"client", "node_modules", ".git", "database.sql"}
        path: pern-project-todo/server
        remote_path: /home/ubuntu/app
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
  